name: 打包构建

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: 检查Git仓库
        uses: actions/checkout@v3
      - name: 校验Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 设定Gradle
        uses: gradle/gradle-build-action@v2
      - name: 安装JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: 上传配置
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: 打包
        run: ./gradlew applyPatches
      - name: 创建Paper核心
        run: ./gradlew createReobfPaperclipJar --stacktrace

      - name: 上传Paper核心
        uses: actions/upload-artifact@v3
        with:
          name: Paper
          path: build/libs/paper-paperclip-*.jar
